name: intake-geopandas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - intake>=0.2
      - geopandas
      - dask
      - pandas
      - aiohttp
      - pyarrow
      - requests
